modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "extendedbogeys"
version = "${version}"
displayName = "Extended Bogeys"
authors = "Rabbitminers RailFanNate Keanes, Matt, Kurocat471"
description = '''
Adding new types of bogeys to create
'''
#logoFile = ""

[[dependencies.extendedbogeys]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedbogeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedbogeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedbogeys]]
modId="create"
mandatory=true
versionRange="[0.5.0.i,)"
ordering="NONE"
side="BOTH"

[[dependencies.extendedbogeys]]
modId="apolloslib"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"

[[dependencies.extendedbogeys]]
modId="polarisfol"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="raposofill"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="isopollafr"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="lisplofaro"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="floraliops"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="oorialsplf"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="olofspiral"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="lapisfloro"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"


[[dependencies.extendedbogeys]]
modId="spiralfool"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"